server:
  port: 8080
  servlet:
    context-path:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: khdscor
    password: mbcsbs21**

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true



  jackson:
    serialization:
      fail-on-empty-beans: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1098001488987-kaidmr0dvjh1q8jhgr2ootr7socn30la.apps.googleusercontent.com
            client-secret: vLVkerP46l8HhI4uxR8RUF0W
            scope:
              - email
              - profile

